#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/mobility-module.h"
#include "ns3/flow-monitor-module.h"
#include "ns3/netanim-module.h"
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <map>

using namespace ns3;

NS_LOG_COMPONENT_DEFINE ("UPFSimulation");

struct NodeData {
    int id;
    double x, y;
};

struct EdgeData {
    int source, target;
    int weight;
};

struct UserData {
    int id;
    int node;
};

void ParseJson(const std::string& filename, std::vector<NodeData>& nodes, std::vector<EdgeData>& edges, std::vector<int>& upfs, std::vector<UserData>& users) {
    // A simplified ad-hoc parser for the specific JSON format generated by our Python script
    std::ifstream ifs(filename);
    if (!ifs.is_open()) {
        NS_FATAL_ERROR("Could not open " << filename);
    }
    std::string content((std::istreambuf_iterator<char>(ifs)), (std::istreambuf_iterator<char>()));
    
    // Naively extract 'upfs' array (assuming [1, 2, 3])
    size_t upfPos = content.find("\"upfs\": [");
    if (upfPos != std::string::npos) {
        size_t endUpfPos = content.find("]", upfPos);
        std::string upfStr = content.substr(upfPos + 9, endUpfPos - (upfPos + 9));
        size_t pos = 0;
        while ((pos = upfStr.find(",")) != std::string::npos) {
            upfs.push_back(std::stoi(upfStr.substr(0, pos)));
            upfStr.erase(0, pos + 1);
        }
        if (!upfStr.empty() && upfStr.find_first_not_of(" \n\r\t") != std::string::npos) {
            upfs.push_back(std::stoi(upfStr));
        }
    }
    
    // We assume 30 nodes (0 to 29). For our simulation, we just create 30 nodes directly
    // and extract links simply. Since parsing JSON strictly without a library in C++ is highly error-prone,
    // we use fixed sizes based on Python output (Nodes: 30) for this skeleton.
    for (int i=0; i<30; ++i) {
        nodes.push_back({i, (double)(rand()%100), (double)(rand()%100)});
    }
    
    // Extract edges naively looking for "source": X, "target": Y, "weight": Z
    size_t edgePos = content.find("\"edges\":");
    size_t currentPos = edgePos;
    while (currentPos != std::string::npos) {
        size_t srcPos = content.find("\"source\": ", currentPos);
        if (srcPos == std::string::npos) break;
        int src = std::stoi(content.substr(srcPos + 10, 5));
        
        size_t tgtPos = content.find("\"target\": ", srcPos);
        int tgt = std::stoi(content.substr(tgtPos + 10, 5));

        size_t wPos = content.find("\"weight\": ", tgtPos);
        int w = std::stoi(content.substr(wPos + 10, 5));
        
        edges.push_back({src, tgt, w});
        currentPos = wPos;
    }
}

int main(int argc, char *argv[]) {
    CommandLine cmd;
    cmd.Parse(argc, argv);

    std::vector<NodeData> nodesData;
    std::vector<EdgeData> edgesData;
    std::vector<int> upfsData;
    std::vector<UserData> usersData;

    ParseJson("topology.json", nodesData, edgesData, upfsData, usersData);
    
    if (nodesData.empty()) {
        NS_LOG_ERROR("Topology data is empty!");
        return 1;
    }

    NodeContainer p2pNodes;
    p2pNodes.Create(nodesData.size());

    // Setup Mobility
    MobilityHelper mobility;
    Ptr<ListPositionAllocator> positionAlloc = CreateObject<ListPositionAllocator>();
    for (const auto& nd : nodesData) {
        positionAlloc->Add(Vector(nd.x, nd.y, 0.0));
    }
    mobility.SetPositionAllocator(positionAlloc);
    // Applying RandomWalk to users (here we apply to all nodes to simulate mobility)
    mobility.SetMobilityModel("ns3::RandomWalk2dMobilityModel",
                              "Bounds", RectangleValue(Rectangle(-50, 50, -50, 50)));
    mobility.Install(p2pNodes);

    InternetStackHelper stack;
    stack.Install(p2pNodes);

    PointToPointHelper p2p;
    p2p.SetDeviceAttribute("DataRate", StringValue("5Mbps"));
    p2p.SetChannelAttribute("Delay", StringValue("2ms"));

    Ipv4AddressHelper address;
    address.SetBase("10.1.0.0", "255.255.255.0");

    // Create links
    int subnet = 1;
    for (const auto& edge : edgesData) {
        NodeContainer linkNodes(p2pNodes.Get(edge.source), p2pNodes.Get(edge.target));
        NetDeviceContainer devices = p2p.Install(linkNodes);
        
        std::string subnetStr = "10.1." + std::to_string(subnet) + ".0";
        address.SetBase(subnetStr.c_str(), "255.255.255.0");
        address.Assign(devices);
        subnet++;
    }

    Ipv4GlobalRoutingHelper::PopulateRoutingTables();

    // Setup UDP Applications (Users -> nearest UPF)
    // For simplicity, we create Echo Servers on all UPF nodes.
    uint16_t port = 9;
    
    for (int upfId : upfsData) {
        UdpEchoServerHelper echoServer(port);
        ApplicationContainer serverApps = echoServer.Install(p2pNodes.Get(upfId));
        serverApps.Start(Seconds(1.0));
        serverApps.Stop(Seconds(10.0));
    }

    // Clients: Random nodes send to Random UPFs
    for (int i = 0; i < 20; ++i) { // 20 UDP flows
        int srcNode = rand() % nodesData.size();
        int targetUpf = upfsData[rand() % upfsData.size()];
        
        Ptr<Ipv4> ipv4 = p2pNodes.Get(targetUpf)->GetObject<Ipv4>();
        Ipv4Address targetAddress = ipv4->GetAddress(1, 0).GetLocal();
        
        UdpEchoClientHelper echoClient(targetAddress, port);
        echoClient.SetAttribute("MaxPackets", UintegerValue(100));
        echoClient.SetAttribute("Interval", TimeValue(Seconds(0.1)));
        echoClient.SetAttribute("PacketSize", UintegerValue(1024));
        
        ApplicationContainer clientApps = echoClient.Install(p2pNodes.Get(srcNode));
        clientApps.Start(Seconds(2.0));
        clientApps.Stop(Seconds(10.0));
    }

    // FlowMonitor
    FlowMonitorHelper flowmon;
    Ptr<FlowMonitor> monitor = flowmon.InstallAll();

    // NetAnim
    AnimationInterface anim("upf-animation.xml");
    
    for (int i = 0; i < (int)nodesData.size(); ++i) {
        bool isUpf = false;
        for (int upfId : upfsData) {
            if (i == upfId) isUpf = true;
        }
        
        if (isUpf) {
            anim.UpdateNodeDescription(p2pNodes.Get(i), "UPF");
            anim.UpdateNodeColor(p2pNodes.Get(i), 255, 0, 0); // Red for UPF
            anim.UpdateNodeSize(i, 4.0, 4.0);
        } else {
            anim.UpdateNodeDescription(p2pNodes.Get(i), "User/Router");
            anim.UpdateNodeColor(p2pNodes.Get(i), 0, 0, 255); // Blue for User
            anim.UpdateNodeSize(i, 2.0, 2.0);
        }
    }

    Simulator::Stop(Seconds(10.0));
    Simulator::Run();

    monitor->SerializeToXmlFile("flowmon.xml", true, true);

    Simulator::Destroy();
    
    std::cout << "ns-3 simulation finished successfully.\n";
    return 0;
}
